"use client"

/**
 * StockHeroImage — verdict-colored full-bleed hero for /analysis/[ticker].
 *
 * Manifesto Rule 9 ("Color is signal, not theme") made tangible: the
 * gradient overlay is keyed off the verdict tier, so HDFCBANK
 * (undervalued, MoS +43.7%) renders an emerald → teal hero while a
 * deeply overvalued name renders amber → rust. The page literally
 * looks different colors for different stocks — users learn to
 * recognize the verdict before reading.
 *
 * Layout:
 *   - Full-bleed 220px (mobile) / 320px (md+) container
 *   - Background image fetched from /api/v1/public/company-image/{ticker}
 *     (Phase 1 endpoint always returns 204 — gradient fallback is the
 *     v1 experience; image backfill is a separate operator task)
 *   - Dark gradient overlay (40% opacity, verdict-colored)
 *   - Giant company initial letter behind the price card when no image
 *   - Floating glass-morphism price card on bottom-left
 *   - Verdict pill + share/save buttons on top-right
 *
 * Non-goals (Phase 1):
 *   - No live intraday change % — backend payload doesn't carry it on
 *     /stock-summary; we omit the chip rather than guess
 *   - No image lazy-loading hint dance — Next/Image with `priority`
 *     would compete with LCP; we use a plain <img loading="lazy"/>
 *     since the gradient fallback is what most users see anyway
 */

import Image from "next/image"
import { useMemo, useState } from "react"

import FreshnessStamp from "@/components/common/FreshnessStamp"
import marqueeHeroes from "@/data/marquee_heroes.json"
import { formatCurrency } from "@/lib/utils"
import { formatMarketCap } from "@/lib/formatters"
import { getLogoFallbackUrl, getLogoUrl } from "@/lib/logoUrl"
import {
  VERDICT_COLORS,
  verdictTierFromMos,
  verdictTierLabel,
} from "@/lib/verdict-colors"

// Hand-curated marquee-50 hero photos (Wikipedia infobox images).
// Generated by `scripts/fetch_marquee_heroes.py`. Tickers absent from
// this map fall through to the existing Option A logo-only treatment.
type MarqueeEntry = { src: string; credit: string; source_url: string }
const MARQUEE_HEROES = marqueeHeroes as unknown as Record<
  string,
  MarqueeEntry | { description?: string }
>
function getMarqueeHero(ticker: string): MarqueeEntry | null {
  const key = (ticker || "").toUpperCase().replace(/\.(NS|BO)$/i, "")
  const entry = MARQUEE_HEROES[key] as MarqueeEntry | undefined
  if (!entry || !entry.src || !entry.credit) return null
  return entry
}

export interface StockHeroImageProps {
  ticker: string
  /** Display ticker (without .NS / .BO suffix). Falls back to `ticker`. */
  displayTicker?: string
  companyName: string
  currentPrice: number
  currency: string
  marginOfSafetyPct?: number | null
  verdict?: string | null
  marketCapCr?: number | null
  /** ISO-8601 timestamp of the quote freshness ("delayed, as of Xm ago"). */
  asOf?: string | null
  /** Optional intraday change % — hidden when null. */
  intradayChangePct?: number | null
}

export default function StockHeroImage({
  ticker,
  displayTicker,
  companyName,
  currentPrice,
  currency,
  marginOfSafetyPct,
  verdict,
  marketCapCr,
  asOf,
  intradayChangePct,
}: StockHeroImageProps) {
  const tier = verdictTierFromMos(marginOfSafetyPct, verdict)
  const palette = VERDICT_COLORS[tier]
  const tierLabel = verdictTierLabel(tier)
  const initial = (companyName || ticker || "?").trim().charAt(0).toUpperCase()
  const safeTicker = (displayTicker ?? ticker).replace(/\.(NS|BO)$/i, "")

  // Image source resolution — start by attempting the backend endpoint.
  // 204 No Content (Phase 1 default) triggers the onError handler which
  // flips us to the gradient + initial fallback. We deliberately do NOT
  // probe with a HEAD request first; one round-trip is cheaper.
  const imageSrc = `/api/v1/public/company-image/${encodeURIComponent(ticker)}`
  const [imageOk, setImageOk] = useState(true)

  // Marquee-50 hand-curated hero photo (Wikipedia infobox). When present
  // it REPLACES the verdict gradient as the visible backdrop and the
  // Option A logo gets demoted to a small chip — see render below. Only
  // ~50 tickers map; everyone else falls through to the existing
  // gradient + logo treatment unchanged.
  const marquee = useMemo(() => getMarqueeHero(ticker), [ticker])
  const [marqueeOk, setMarqueeOk] = useState(true)
  const showMarquee = !!marquee && marqueeOk

  // Real-company-logo resolution chain — Brandfetch (when configured)
  // -> Google favicon -> giant-letter fallback. The chain is driven by
  // two pieces of state: `logoSrc` is what <Image> is currently asked
  // to render, and `logoFailed` flips true after we've exhausted both
  // remote sources, signalling the letter fallback. Tickers absent
  // from `ticker_domains.json` start with `logoSrc === null` and we
  // skip straight to the letter (no failed request fired).
  const initialLogo = useMemo(() => getLogoUrl(ticker, 128), [ticker])
  const [logoSrc, setLogoSrc] = useState<string | null>(initialLogo)
  const [logoFailed, setLogoFailed] = useState(false)
  const handleLogoError = () => {
    const fallback = getLogoFallbackUrl(ticker)
    if (fallback && fallback !== logoSrc) {
      setLogoSrc(fallback)
    } else {
      setLogoFailed(true)
    }
  }
  const showLogo = !!logoSrc && !logoFailed

  // Intraday change chip — only render when the backend actually sent
  // a number. No fake zeros.
  const showIntraday =
    intradayChangePct != null && Number.isFinite(intradayChangePct)
  const intradayUp = (intradayChangePct ?? 0) >= 0

  return (
    <section
      aria-label={`${companyName} hero summary`}
      className={[
        "relative w-full overflow-hidden rounded-2xl",
        "h-[220px] md:h-[320px]",
        // Solid gradient base — always visible, image layers on top.
        "bg-gradient-to-br",
        palette.from,
        palette.to,
      ].join(" ")}
    >
      {/* Marquee-50 hero photo — Wikipedia infobox image, hand-curated.
          When present this REPLACES the verdict gradient as the visible
          backdrop. Falls through to the legacy backend image / gradient
          chain on error. */}
      {showMarquee && marquee && (
        <>
          <img
            src={marquee.src}
            alt=""
            aria-hidden
            loading="eager"
            decoding="async"
            onError={() => setMarqueeOk(false)}
            className="absolute inset-0 w-full h-full object-cover"
          />
          {/* Top-to-bottom darkening so the white price text stays legible. */}
          <div
            aria-hidden
            className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/40 to-transparent"
          />
        </>
      )}

      {/* Background image — hidden when 204/error or when the marquee
          photo is the active backdrop. */}
      {!showMarquee && imageOk && (
        <img
          src={imageSrc}
          alt=""
          aria-hidden
          loading="lazy"
          decoding="async"
          onError={() => setImageOk(false)}
          className="absolute inset-0 w-full h-full object-cover opacity-70"
        />
      )}

      {/* Dark overlay — strengthens contrast for the price card text.
          Slightly stronger than the spec's 40% so the verdict-colored
          gradient still reads through. Suppressed when the marquee
          photo is shown — that path uses its own black gradient above. */}
      {!showMarquee && (
        <div
          aria-hidden
          className={[
            "absolute inset-0",
            "bg-gradient-to-br",
            palette.from,
            palette.to,
            "opacity-60",
          ].join(" ")}
        />
      )}

      {/* Marquee path: real company logo demoted to a top-left chip
          floating on top of the hero photo. */}
      {showMarquee && showLogo && (
        <div
          data-testid="hero-company-logo"
          className="absolute top-3 left-3 md:top-4 md:left-4"
        >
          <div
            className={[
              "relative",
              "h-12 w-12 md:h-14 md:w-14",
              "rounded-xl bg-white/95",
              "shadow-md ring-1 ring-black/10",
              "p-1.5",
            ].join(" ")}
          >
            <Image
              src={logoSrc as string}
              alt=""
              aria-hidden
              fill
              sizes="(min-width: 768px) 56px, 48px"
              className="object-contain"
              onError={handleLogoError}
              unoptimized
            />
          </div>
        </div>
      )}

      {/* Legacy (no marquee) path — real company logo centered behind
          the price card as the visual anchor. The double-onError chain
          swaps to favicon then surrenders to the letter. */}
      {!showMarquee && !imageOk && showLogo && (
        <div
          aria-hidden
          data-testid="hero-company-logo"
          className="absolute inset-0 flex items-center justify-center"
        >
          <div
            className={[
              "relative",
              "h-20 w-20 md:h-24 md:w-24",
              "rounded-2xl bg-white/90 dark:bg-white/85",
              "shadow-lg ring-1 ring-white/40",
              "p-2 md:p-3",
            ].join(" ")}
          >
            <Image
              src={logoSrc as string}
              alt=""
              fill
              sizes="(min-width: 768px) 96px, 80px"
              className="object-contain"
              onError={handleLogoError}
              unoptimized
            />
          </div>
        </div>
      )}

      {/* Giant company initial — only when neither the backend image
          NOR a real logo is available, AND we don't have a marquee
          photo (marquee path doesn't need a fallback anchor). */}
      {!showMarquee && !imageOk && !showLogo && (
        <div
          aria-hidden
          className={[
            "absolute inset-0 flex items-center justify-center",
            "font-editorial font-bold select-none",
            "text-[160px] md:text-[240px] leading-none",
            palette.text,
            "opacity-20",
          ].join(" ")}
        >
          {initial}
        </div>
      )}

      {/* Image attribution — required by CC-BY-SA for Wikipedia photos. */}
      {showMarquee && marquee && (
        <a
          href={marquee.source_url}
          target="_blank"
          rel="noopener noreferrer nofollow"
          className="absolute bottom-1.5 right-2 text-[10px] md:text-xs text-white/60 hover:text-white/90 transition-colors"
          title={marquee.credit}
        >
          Image: {marquee.credit}
        </a>
      )}

      {/* Top-right — verdict pill + action buttons */}
      <div className="absolute top-3 right-3 md:top-4 md:right-4 flex items-center gap-2">
        <span
          data-testid="hero-verdict-pill"
          className={[
            "inline-flex items-center gap-1.5 rounded-full",
            "px-3 py-1 text-[11px] md:text-xs font-semibold uppercase tracking-wider",
            "bg-white/15 backdrop-blur-md border border-white/25",
            palette.text,
          ].join(" ")}
        >
          <span
            aria-hidden
            className={`inline-block w-1.5 h-1.5 rounded-full ${palette.bar}`}
          />
          {tierLabel}
        </span>
      </div>

      {/* Bottom-left — glass-morphism price card */}
      <div className="absolute bottom-3 left-3 md:bottom-5 md:left-5 right-3 md:right-auto md:max-w-md">
        <div
          className={[
            "rounded-xl border border-white/20",
            "bg-white/10 dark:bg-black/20 backdrop-blur-lg",
            "px-4 py-3 md:px-4 md:py-4",
            "shadow-lg",
          ].join(" ")}
        >
          <div className="flex items-baseline gap-2 flex-wrap">
            <span
              className={`font-mono font-bold text-xl md:text-2xl tracking-tight ${palette.text}`}
            >
              {safeTicker}
            </span>
            <span
              className={`text-xs md:text-sm font-medium opacity-90 ${palette.text}`}
            >
              {companyName}
            </span>
          </div>

          <div className="mt-1 flex items-baseline gap-2 flex-wrap">
            <span
              className={`font-mono tabular-nums font-bold text-2xl md:text-3xl ${palette.text}`}
            >
              {currentPrice > 0
                ? formatCurrency(currentPrice, currency)
                : "—"}
            </span>
            {showIntraday && (
              <span
                className={[
                  "font-mono tabular-nums text-sm font-semibold",
                  intradayUp ? "text-emerald-200" : "text-rose-200",
                ].join(" ")}
                aria-label={`Intraday change ${intradayChangePct!.toFixed(2)} percent`}
              >
                {intradayUp ? "▲" : "▼"} {Math.abs(intradayChangePct!).toFixed(2)}%
              </span>
            )}
          </div>

          <div className="mt-2 flex items-center gap-2 flex-wrap text-[11px] md:text-xs">
            {marketCapCr != null && marketCapCr > 0 && (
              <span
                className={`px-2 py-0.5 rounded-full bg-white/10 border border-white/15 ${palette.text}`}
              >
                Mkt Cap {formatMarketCap(marketCapCr)}
              </span>
            )}
            <FreshnessStamp
              timestamp={asOf}
              prefix="Delayed, as of"
              fallback="Quote freshness unknown"
              className={`${palette.text} opacity-90`}
            />
          </div>
        </div>
      </div>
    </section>
  )
}
