// frontend/src/components/DataUnderReview.tsx
// Fail-closed UI for stocks where backend validation flagged a critical
// data-quality issue. Shown INSTEAD of the normal stock page — never
// alongside broken numbers.
//
// Rule: no price, no fair value, no margin of safety on this page.
// The whole point is to not ship questionable financial figures.
import Link from "next/link"

interface DataUnderReviewProps {
  symbol: string
  lastValidatedAt?: string | null
  reason?: string | null
}

export default function DataUnderReview({
  symbol,
  lastValidatedAt,
}: DataUnderReviewProps) {
  const display = symbol.toUpperCase().replace(/\.(NS|BO)$/i, "")

  return (
    <div className="max-w-2xl mx-auto px-4 py-16 sm:py-24">
      <div className="bg-white rounded-2xl border border-amber-200 shadow-sm p-8 sm:p-10">
        <div className="flex items-center gap-3 mb-5">
          <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center text-amber-600 font-bold text-lg">
            !
          </div>
          <h1 className="text-xl sm:text-2xl font-bold text-gray-900">
            Data under review
          </h1>
        </div>

        <p className="text-gray-700 leading-relaxed mb-4">
          Model output for <span className="font-semibold">{display}</span> is
          being recalibrated. We're holding back analysis figures until
          data-quality checks pass.
        </p>
        <p className="text-gray-500 text-sm mb-6">
          This protects you from seeing numbers that could be wrong due to
          upstream data issues. Valid analysis will return automatically once
          checks pass on the next refresh.
        </p>

        {lastValidatedAt && (
          <p className="text-xs text-gray-400 mb-6">
            Last validation attempt:{" "}
            <span className="font-mono">
              {new Date(lastValidatedAt).toLocaleString()}
            </span>
          </p>
        )}

        <div className="pt-6 border-t border-gray-100">
          <p className="text-sm text-gray-600 mb-3">
            While you wait, explore other validated stocks:
          </p>
          <div className="flex flex-wrap gap-2">
            {["TCS", "INFY", "HDFCBANK", "RELIANCE", "ITC"]
              .filter((t) => t !== display)
              .map((t) => (
                <Link
                  key={t}
                  href={`/stocks/${t}/fair-value`}
                  className="px-3 py-1.5 text-xs font-medium text-gray-700 bg-gray-50 hover:bg-gray-100 rounded-lg border border-gray-200 transition"
                >
                  {t}
                </Link>
              ))}
          </div>
          <p className="text-xs text-gray-400 mt-6">
            YieldIQ is an analytical tool, not investment advice. All outputs
            are generated by quantitative models using public data. YieldIQ is
            not a SEBI-registered Research Analyst or Investment Adviser.
          </p>
        </div>
      </div>
    </div>
  )
}
