// frontend/src/components/StockDisclaimer.tsx
// Universal SEBI-compliant disclaimer for any page that surfaces stock
// analysis output (DCF, screener results, portfolio MoS, etc.).
//
// Keep the exact phrasing consistent across the product — legal/SEBI
// reviews this. Do not edit without sign-off.
export default function StockDisclaimer({
  variant = "default",
}: {
  variant?: "default" | "compact"
}) {
  if (variant === "compact") {
    return (
      <p className="text-[10px] text-gray-400 leading-relaxed">
        YieldIQ is an analytical tool, not investment advice. Model output
        only — YieldIQ is not registered with SEBI as an investment
        adviser or research analyst.
      </p>
    )
  }

  return (
    <div className="mt-8 pt-6 border-t border-gray-100">
      <p className="text-xs text-gray-500 leading-relaxed">
        YieldIQ is an analytical tool, not investment advice. All outputs
        are generated by quantitative models using public data. YieldIQ is
        not a SEBI-registered Research Analyst or Investment Adviser.
        Consult a SEBI-registered adviser before making investment decisions.
      </p>
    </div>
  )
}
