# Top 200 NSE tickers
# Maps NSE ticker -> yfinance symbol
def get_yf_symbol(ticker):
    """Add .NS suffix for NSE stocks."""
    special = {
        'M&M': 'M&M.NS',
        'BAJAJ-AUTO': 'BAJAJ-AUTO.NS',
        'MCDOWELL-N': 'MCDOWELL-N.NS',
    }
    return special.get(ticker, f'{ticker}.NS')


TOP_200 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY",
    "ICICIBANK", "HINDUNILVR", "ITC", "SBIN",
    "BHARTIARTL", "KOTAKBANK", "LT", "BAJFINANCE",
    "ASIANPAINT", "AXISBANK", "MARUTI", "TITAN",
    "SUNPHARMA", "NESTLEIND", "WIPRO", "ULTRACEMCO",
    "HCLTECH", "POWERGRID", "NTPC", "ONGC",
    "COALINDIA", "BAJAJFINSV", "DIVISLAB", "DRREDDY",
    "CIPLA", "EICHERMOT", "ADANIENT", "ADANIPORTS",
    "TATASTEEL", "JSWSTEEL", "HINDALCO", "VEDL",
    "TATACONSUM", "BRITANNIA", "DABUR", "MARICO",
    "COLPAL", "PIDILITIND", "BERGEPAINT", "HAVELLS",
    "GODREJCP", "BAJAJ-AUTO", "HEROMOTOCO",
    "TVSMOTOR", "M&M", "ASHOKLEY",
    "BOSCHLTD", "APOLLOTYRE", "INDUSINDBK",
    "FEDERALBNK", "BANDHANBNK", "IDFCFIRSTB",
    "CANBK", "UNIONBANK", "PNB", "BANKBARODA",
    "CHOLAFIN", "MUTHOOTFIN", "MANAPPURAM",
    "LTIM", "TECHM", "MPHASIS", "PERSISTENT",
    "COFORGE", "OFSS", "KPIT", "TATAELXSI",
    "APOLLOHOSP", "MAXHEALTH", "FORTIS", "ALKEM",
    "TORNTPHARM", "AUROPHARMA", "LUPIN", "BIOCON",
    "IPCALAB", "ETERNAL", "NYKAA", "IRCTC",
    "INDIGO", "GRASIM", "AMBUJACEM", "ACC",
    "SHREECEM", "TATAPOWER", "ADANIPOWER",
    "CESC", "TORNTPOWER", "BPCL", "HINDPETRO",
    "IOC", "GAIL", "PETRONET", "JUBLFOOD",
    "DLF", "GODREJPROP", "OBEROIRLTY", "PRESTIGE",
    "NMDC", "HINDZINC", "NATIONALUM", "PAGEIND",
    "TRENT", "SIEMENS", "ABB", "CUMMINSIND",
    "THERMAX", "SRF", "DEEPAKNTR", "PIIND",
    "IRFC", "PFC", "REC", "HUDCO", "ZYDUSLIFE",
    "GLAXO", "PFIZER", "ABBOTINDIA", "LICHSGFIN",
    "CANFINHOME", "MFSL", "HDFCLIFE", "SBILIFE",
    "ICICIGI", "TATAMOTORS",
    # ---- expansion batch (Apr 2026) ----
    "BAJAJHLDNG", "MCDOWELL-N", "RADICO",
    "UNITDSPR", "VOLTAS", "WHIRLPOOL",
    "DIXON", "AMBER",
    "ASTRAL", "SUPREMEIND", "POLYCAB",
    "KANSAINER", "AKZOINDIA", "LALPATHLAB",
    "METROPOLIS", "DRHP", "SUVENPHAR",
    "FLUOROCHEM", "NACLIND", "AAVAS",
    "HOMEFIRST", "APTUS", "CREDITACC",
    "SPANDANA", "EQUITASBNK", "UJJIVANSFB",
    "SURYAROSNI", "ORIENTELEC", "BATAINDIA",
    "RELAXO", "VSTIND", "GODFRYPHLP",
    "IEX", "CAMS", "CDSL", "BSE",
    "MCXINDIA", "LICI",
    "GICRE", "NIACL", "STARHEALTH",
    "YESBANK", "RBLBANK", "KARURVYSYA",
    "CITYUNIONBK", "DCBBANK", "SOUTHBANK",
    "IDBI", "J&KBANK", "LAKSHVILAS",
    "APLAPOLLO", "JSPL", "JINDALSTEL",
    "RATNAMANI", "WELSPUNIND", "GRINDWELL",
    "SCHAEFFLER", "TIMKEN", "SKF",
    "ELGIEQUIP", "GREAVESCOT", "KIRLOSKAR",
    "CERA", "KAJARIA", "SOMANYCER",
    "ORIENTCEM", "HEIDELBERG", "JKCEMENT",
    "NUVOCO", "RAMCOCEM", "STAR",
    "SUNTV", "ZEEL", "NETWORK18",
    "TV18BRDCST", "PVRINOX",
]

# Dedupe while preserving order (BERGEPAINT and MFSL were already in the list)
_seen = set()
TOP_200 = [t for t in TOP_200 if not (t in _seen or _seen.add(t))]

