"use client"

// /auth/verify — landing page for the email-verification link.
//
// Token arrives in ?token=… (the link is generated by
// backend/services/verification_service.send_verification_email).
// We POST it to GET /api/v1/auth/verify/confirm and render
// success / failure inline.
//
// This page is unauthenticated by design — the user clicks the link
// from their inbox and shouldn't have to log in first. The backend
// validates the HMAC and flips users_meta.email_verified for the uid
// embedded in the token.

import { useEffect, useState, Suspense } from "react"
import { useSearchParams } from "next/navigation"
import Link from "next/link"
import api from "@/lib/api"
import { useAuthStore } from "@/store/authStore"

type Status = "idle" | "checking" | "ok" | "err"

function VerifyInner() {
  const params = useSearchParams()
  const setEmailVerified = useAuthStore((s) => s.setEmailVerified)
  const [status, setStatus] = useState<Status>("idle")
  const [message, setMessage] = useState<string>("")

  useEffect(() => {
    const token = params.get("token")
    if (!token) {
      setStatus("err")
      setMessage("Missing verification token. Open the link from your email again.")
      return
    }
    let alive = true
    setStatus("checking")
    api
      .get("/api/v1/auth/verify/confirm", { params: { token } })
      .then((r) => {
        if (!alive) return
        setStatus("ok")
        setMessage(r.data?.email ? `Verified ${r.data.email}.` : "Email verified.")
        // Update the local store so the banner disappears immediately
        // if the user has a logged-in session in this browser.
        setEmailVerified(true)
      })
      .catch((err) => {
        if (!alive) return
        const detail = err?.response?.data?.detail
        setStatus("err")
        setMessage(
          typeof detail === "string"
            ? detail
            : "Verification failed. The link may have expired — request a new one from your account.",
        )
      })
    return () => {
      alive = false
    }
  }, [params, setEmailVerified])

  return (
    <main className="min-h-screen flex items-center justify-center px-4 py-12">
      <div className="max-w-md w-full bg-bg dark:bg-surface border border-border rounded-2xl p-8 text-center space-y-4">
        <h1 className="text-xl font-bold text-ink">Email verification</h1>

        {status === "checking" && (
          <p className="text-sm text-body">Confirming your email…</p>
        )}

        {status === "ok" && (
          <>
            <div className="text-3xl" aria-hidden>
              {"✓"}
            </div>
            <p className="text-sm text-body">{message}</p>
            <p className="text-sm text-body">
              Paid upgrades, API access, and exports are now unlocked.
            </p>
            <Link
              href="/home"
              className="inline-block py-2.5 px-5 bg-blue-600 text-white text-sm font-semibold rounded-xl hover:bg-blue-700 transition"
            >
              Return to YieldIQ
            </Link>
          </>
        )}

        {status === "err" && (
          <>
            <div className="text-3xl" aria-hidden>
              {"⚠"}
            </div>
            <p className="text-sm text-red-700 dark:text-red-300">{message}</p>
            <Link
              href="/account"
              className="inline-block py-2.5 px-5 bg-blue-600 text-white text-sm font-semibold rounded-xl hover:bg-blue-700 transition"
            >
              Go to account
            </Link>
          </>
        )}
      </div>
    </main>
  )
}

export default function VerifyPage() {
  return (
    <Suspense
      fallback={
        <main className="min-h-screen flex items-center justify-center">
          <p className="text-sm text-caption">Loading…</p>
        </main>
      }
    >
      <VerifyInner />
    </Suspense>
  )
}
