"""Portfolio Updates Feed (P0 #1, 2026-05-25).

Per-ticker, categorised event stream surfaced as the Portfolio > Updates
tab. Headlines and detail strings are generated by `templates.py` —
template-only, NO LLM calls (zero ongoing cost).

Categories: earnings, valuations, intrinsic_updates, dividends,
insider_trading, risk_legal, other.

SEBI-safe by construction: templates never include buy/sell/hold/target.
"""
