"""Phase 0 sample generator for multilingual AI summary review.

Generates AI summaries in en/hi/ta/mr for 5 representative stocks
(TCS, RELIANCE, INFY, HDFCBANK, ITC) and writes them side-by-side to
``docs/multilingual_samples_for_review.md``.

These samples are the artefact a native-speaker reviewer signs off on
BEFORE the MULTILINGUAL_SUMMARIES_ENABLED feature flag is flipped in
Railway. This script does NOT write to ``analysis_cache``,
``model_predictions_history``, or any other prod table — it produces
a markdown document only.

Behaviour:
  * If GROQ_API_KEY is set (in env or .env.local), real summaries are
    generated by hitting Groq.
  * If GROQ_API_KEY is missing, the script writes a clearly-labelled
    MOCK output so the PR can still build, with a TODO instructing the
    user to regenerate before review.

Usage:
  python scripts/generate_multilingual_samples.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_PATH = REPO_ROOT / "docs" / "multilingual_samples_for_review.md"

SAMPLE_TICKERS = ["TCS", "RELIANCE", "INFY", "HDFCBANK", "ITC"]
LANGUAGES = ["en", "hi", "ta", "mr"]


def _load_env_local() -> None:
    """Best-effort load of .env.local — no python-dotenv dependency.
    Only sets keys that aren't already in os.environ."""
    env_local = REPO_ROOT / ".env.local"
    if not env_local.exists():
        return
    try:
        for line in env_local.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val
    except Exception as exc:
        print(f"[warn] could not parse .env.local: {exc}", file=sys.stderr)


# Mock English summaries used when no Groq key is available. These
# are NOT representative of actual model output — they exist purely
# so the rendered review document has structure for the reviewer to
# evaluate the layout. Real samples must be regenerated before any
# native-speaker review.
MOCK_ENGLISH = {
    "TCS": (
        "Model-generated description of metrics. Not investment "
        "advice. TCS trades at 3500 vs fair value 3800; MoS 8%. "
        "ROE 45%, Piotroski 7/9, YieldIQ score 78/100."
    ),
    "RELIANCE": (
        "Model-generated description of metrics. Not investment "
        "advice. RELIANCE trades at 2900 vs fair value 3100; MoS 6%. "
        "ROE 9%, Piotroski 6/9, YieldIQ score 64/100."
    ),
    "INFY": (
        "Model-generated description of metrics. Not investment "
        "advice. INFY trades at 1400 vs fair value 1650; MoS 15%. "
        "ROE 31%, Piotroski 8/9, YieldIQ score 81/100."
    ),
    "HDFCBANK": (
        "Model-generated description of metrics. Not investment "
        "advice. HDFCBANK trades at 1500 vs fair value 1750; MoS 14%. "
        "ROE 17%, Piotroski 7/9, YieldIQ score 76/100."
    ),
    "ITC": (
        "Model-generated description of metrics. Not investment "
        "advice. ITC trades at 410 vs fair value 470; MoS 12%. "
        "ROE 28%, Piotroski 7/9, YieldIQ score 73/100."
    ),
}


def _load_language_prompts():
    """Load language_prompts.py standalone — its parent package
    ``backend.services.analysis`` has an eager __init__ that pulls
    pydantic/screener/etc., which we don't need for prompt strings."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "yq_lang_prompts_standalone",
        str(
            REPO_ROOT
            / "backend" / "services" / "analysis" / "language_prompts.py"
        ),
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _render_mock_translation(ticker: str, lang: str, en: str) -> str:
    """Build a clearly-marked mock translation for a given language."""
    DISCLAIMERS = _load_language_prompts().DISCLAIMERS
    if lang == "en":
        return en
    placeholder = {
        "hi": f"[MOCK हिंदी अनुवाद — {ticker}] {en}",
        "ta": f"[MOCK தமிழ் மொழிபெயர்ப்பு — {ticker}] {en}",
        "mr": f"[MOCK मराठी भाषांतर — {ticker}] {en}",
    }[lang]
    return f"{placeholder}\n\n{DISCLAIMERS[lang]}"


def _generate_real(ticker: str) -> dict[str, str]:
    """Hit Groq for English summary then translate into hi/ta/mr.

    For Phase 0 sample generation we don't have a full AnalysisResponse
    on hand, so we approximate by feeding the model a tiny static
    data block per ticker. The PR README explicitly states samples are
    illustrative — Phase 1 review can still validate prompt register
    and disclaimer placement, which is what we need."""
    from groq import Groq  # type: ignore[import-not-found]
    _lp = _load_language_prompts()
    DISCLAIMERS = _lp.DISCLAIMERS
    LANGUAGE_PROMPTS = _lp.LANGUAGE_PROMPTS

    client = Groq(api_key=os.environ["GROQ_API_KEY"].strip())

    # Generate English summary first, using a stripped-down version
    # of NarrativeMixin's user prompt.
    en_user = (
        f"Describe stock {ticker} in ONE sentence (max 260 characters) "
        "using only the following representative data block. Do NOT "
        "use verdict words. No preamble, no markdown.\n\n"
        f"Data:\nTicker: {ticker}\nSector: representative Indian large-cap\n"
        "Current Price: 1500 | Fair Value: 1700 | MoS: 12%\n"
        "ROE: 22% | Piotroski: 7/9 | YieldIQ score: 75/100\n"
        "\nDescription:"
    )
    en_resp = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": LANGUAGE_PROMPTS["en"]},
            {"role": "user", "content": en_user},
        ],
        max_tokens=180,
        temperature=0.2,
    )
    english = (en_resp.choices[0].message.content or "").strip()

    out = {"en": english}
    for lang in ("hi", "ta", "mr"):
        tr_resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": LANGUAGE_PROMPTS[lang]},
                {
                    "role": "user",
                    "content": (
                        "Translate this SEBI-compliant English stock "
                        "summary into the target language. Preserve "
                        "all numbers exactly. Append the mandatory "
                        "native-language disclaimer at the end.\n\n"
                        f"English summary:\n{english}\n\nTranslation:"
                    ),
                },
            ],
            max_tokens=400,
            temperature=0.2,
        )
        text = (tr_resp.choices[0].message.content or "").strip()
        if DISCLAIMERS[lang] not in text:
            text = f"{text}\n\n{DISCLAIMERS[lang]}"
        out[lang] = text
    return out


def render_markdown(samples: dict[str, dict[str, str]], *, mocked: bool) -> str:
    lines: list[str] = []
    lines.append("# Multilingual AI Summary Samples — Native-Speaker Review")
    lines.append("")
    if mocked:
        lines.append("> **WARNING — MOCK OUTPUT.**")
        lines.append(
            "> No GROQ_API_KEY was available when this document was "
            "generated, so the per-language sections below contain "
            "placeholder strings, not real model output. **Before any "
            "native-speaker review, the maintainer must re-run "
            "`python scripts/generate_multilingual_samples.py` with "
            "`GROQ_API_KEY` exported and re-commit this file.**"
        )
        lines.append("")
    else:
        lines.append(
            "These summaries were generated by Groq using the prompts "
            "in `backend/services/analysis/language_prompts.py`. "
            "Native speakers should review each non-English block for: "
            "register (formal/respectful), terminology (financial), "
            "Hinglish bleed, factual integrity (numbers preserved), "
            "and disclaimer placement."
        )
        lines.append("")

    lines.append("## Review checklist (per language, per stock)")
    lines.append("")
    lines.append("- [ ] Register is formal / respectful (no colloquial)")
    lines.append("- [ ] Financial terms are correct in target language")
    lines.append("- [ ] No Hinglish / English bleed where avoidable")
    lines.append("- [ ] All numbers from the English version preserved")
    lines.append("- [ ] Disclaimer present and rendered correctly")
    lines.append("- [ ] No SEBI banned vocabulary leaked through")
    lines.append("")

    for ticker in SAMPLE_TICKERS:
        lines.append(f"## {ticker}")
        lines.append("")
        block = samples.get(ticker, {})
        for lang in LANGUAGES:
            label = {
                "en": "English (authoritative)",
                "hi": "Hindi (हिंदी)",
                "ta": "Tamil (தமிழ்)",
                "mr": "Marathi (मराठी)",
            }[lang]
            lines.append(f"### {label}")
            lines.append("")
            lines.append("```")
            lines.append(block.get(lang, "(missing)"))
            lines.append("```")
            lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    _load_env_local()
    has_key = bool(os.environ.get("GROQ_API_KEY", "").strip())

    samples: dict[str, dict[str, str]] = {}
    if has_key:
        print("[info] GROQ_API_KEY found — generating real samples")
        try:
            for ticker in SAMPLE_TICKERS:
                print(f"[info] generating {ticker} ...")
                samples[ticker] = _generate_real(ticker)
            mocked = False
        except Exception as exc:
            print(
                f"[warn] real generation failed ({type(exc).__name__}: "
                f"{exc}); falling back to mock output",
                file=sys.stderr,
            )
            samples = {}
            has_key = False

    if not has_key:
        print(
            "[info] no GROQ_API_KEY — emitting MOCK samples. "
            "Re-run with GROQ_API_KEY set before native-speaker review."
        )
        for ticker in SAMPLE_TICKERS:
            en = MOCK_ENGLISH[ticker]
            samples[ticker] = {
                lang: _render_mock_translation(ticker, lang, en)
                for lang in LANGUAGES
            }

    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.write_text(
        render_markdown(samples, mocked=not has_key),
        encoding="utf-8",
    )
    print(f"[ok] wrote {DOCS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
